PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures

  Fasterer:
    enabled: true
    on_warn: fail
    problem_on_unmodified_line: ignore

  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/db/structure.sql' # Ignore trailing whitespace in generated files
